sudo: required

language: generic

env:
  global:
  - GOSS_VERSION=0.3.5
  - GOSS_PATH=/usr/local/bin/goss

services:
  - docker

before_install:
    - curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec 

script:
  - docker build -t rahulinux/awscli .
  - docker run --name awscli -dt rahulinux/awscli sh
  - inspec exec test-awscli.rb docker://awscli
  

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]
    then
       echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
       docker push rahulinux/awscli
    fi
