sudo: required

language: generic

env:
  global:
  - IMAGE=awscli 

services:
  - docker

before_install:
    - curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec 

script:
    -  docker build -t rahulinux/$IMAGE -f Dockerfile.$IMAGE .
    -  docker run --name $IMAGE -dt rahulinux/$IMAGE sh
    -  inspec exec test-$IMAGE.rb -t docker://$IMAGE
  

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]
    then
       echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
       docker push rahulinux/$IMAGE
    fi
